wandb_version: 1

Initialize_Label_Model:
  desc: null
  value: ''
Initialize_Label_Model_Dir:
  desc: null
  value: ''
Initialize_Label_With_Another_Model:
  desc: null
  value: false
Iteration:
  desc: null
  value: 1000
Label_Model_Timestamp:
  desc: null
  value: -1
Momentum_y:
  desc: null
  value: 0.9
Sequential_Generation:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1701835217
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
batch_real:
  desc: null
  value: 256
batch_syn:
  desc: null
  value: 500
batch_train:
  desc: null
  value: 128
buffer_path:
  desc: null
  value: ../buffer_storage
canvas_samples:
  desc: null
  value: 1
canvas_size:
  desc: null
  value: 2
cfg:
  desc: null
  value: ../configs/MNIST/ConvIN/IPC10.yaml
current_max_start_epoch:
  desc: null
  value: 10
data_path:
  desc: null
  value: ../dataset
dataset:
  desc: null
  value: MNIST
dc_aug_param:
  desc: null
  value: null
device:
  desc: null
  value: cuda
dsa:
  desc: null
  value: true
dsa_param:
  desc: null
  value: <utils.utils_baseline.ParamDiffAug object at 0x7f46aa8681f0>
dsa_strategy:
  desc: null
  value: color_crop_cutout_flip_scale_rotate
ema_decay:
  desc: null
  value: 0.9995
epoch_eval_train:
  desc: null
  value: 1000
eval_it:
  desc: null
  value: 1000
eval_mode:
  desc: null
  value: S
expansion_end_epoch:
  desc: null
  value: 1000
expert_epochs:
  desc: null
  value: 2
force_save:
  desc: null
  value: false
im_size:
  desc: null
  value:
  - 28
  - 28
ipc:
  desc: null
  value: 10
load_all:
  desc: null
  value: false
lr_img:
  desc: null
  value: 1000
lr_init:
  desc: null
  value: 0.01
lr_lr:
  desc: null
  value: 1.0e-05
lr_teacher:
  desc: null
  value: 0.01
lr_y:
  desc: null
  value: 2.0
max_experts:
  desc: null
  value: null
max_files:
  desc: null
  value: null
max_start_epoch:
  desc: null
  value: 4
min_start_epoch:
  desc: null
  value: 0
model:
  desc: null
  value: ConvNet
no_aug:
  desc: null
  value: false
num_eval:
  desc: null
  value: 1
parall_eva:
  desc: null
  value: false
pix_init:
  desc: null
  value: samples_predicted_correctly
project:
  desc: null
  value: MNIST_ipc10
record_loss:
  desc: null
  value: false
res:
  desc: null
  value: 32
skip_first_eva:
  desc: null
  value: true
subset:
  desc: null
  value: imagenette
syn_steps:
  desc: null
  value: 20
texture:
  desc: null
  value: false
threshold:
  desc: null
  value: 1.0
zca:
  desc: null
  value: true
zca_trans:
  desc: null
  value: ZCAWhitening()
